name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# GitHub Actions does not support Docker, PostgreSQL server on Windows, macOS :(

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.ref == 'refs/heads/trunk' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout xalan-java'
      uses: actions/checkout@v4.1.1
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v4.1.0
      with:
        distribution: zulu
        java-version: 8
    - name: 'Build Xalan jars'
      run: |
        mvn --no-transfer-progress clean compile site verify
    - uses: actions/checkout@v4.1.1
      name: 'Checkout xalan-test'
      with:
        repository: apache/xalan-test
        path: xalan-test
        ref: master
    - name: 'Cheat xalan-test up to be sibling of xalan-java'
      run: |
        mv xalan-test ..; ls ..
    - name: 'Run xalan-test tests'
      working-directory: ../xalan-test
      run: |
        ls; ant -debug jar extensions.classes smoketest apitest -Dxalan.relpath=../xalan-java -Dparserjar=../xalan-java/lib/xercesImpl-2.12.2.jar -Dxml-apis.jar=../xalan-java/lib/xml-apis-1.4.01.jar
  build_and_release:
    name: "Build and Release"
    uses: Alfresco/alfresco-build-tools/.github/workflows/build-and-release-maven.yml@v5.17.1
    secrets: inherit
    needs: test
    with:
      java-version: 8
      skip-tests: true
      auto-release: false
